[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = -std=gnu++17
build_unflags = -std=gnu++11
lib_deps =
    bblanchon/ArduinoJson@^7.0.0
monitor_speed = 115200

[env:native]
platform = native
build_flags = -std=gnu++17 -I src
lib_deps =
    bblanchon/ArduinoJson@^7.0.0
