# -*- coding: utf-8 -*-
"""Sheet notes for power_input.kicad_sch.

Recovered 2026-09-14 from the committed sheet, after the original scratchpad module was
lost to a filename collision with the rails notes module.  Fidelity was proved by
regenerating the sheet byte-for-byte against the committed copy before any change was made.
"""
NOTE_FONT = 1.0

TEXTBOXES = [
    ('INPUT FILTER ORDER: fuse -> reverse-polarity FET -> TVS -> CM choke -> pi filter -> bulk\nThe TVS (D2) must come BEFORE the choke.  Surge clamping degrades with series inductance\nbetween the entry point and the clamp, so any inductance ahead of D2 lets the clamped\nvoltage overshoot.\nThe choke (L2) must come BEFORE the pi filter.  The common-mode noise being blocked\noriginates INSIDE the board -- it is the boost converter on the rails sheet -- so the choke\nhas to sit between the switcher and the harness, not out at the connector.',
     177.8, 45.72, 103.19, 14.79),
    ("SYMBOL AND PIN-NUMBER NOTES (this sheet was authored as text, not drawn in the GUI)\nQ1 uses Transistor_FET:Q_PMOS_GSD, not Device:Q_PMOS_GSD -- the latter does not exist in KiCad\n10.  Device:Q_PMOS does exist, but its pin NUMBERS are the letters D / G / S, which match no\nstock footprint; Q_PMOS_GSD numbers them 1 = G, 2 = S, 3 = D so a real footprint can be assigned.\nL2 uses Device:L_Coupled, which does exist in KiCad 10.  Its pins are 1 = winding A left,\n2 = winding A right, 3 = winding B left, 4 = winding B right.  So winding A is pins 1-2 and\ncarries the FEED (VBAT_PROT -> VBAT_F); winding B is pins 3-4 and carries the RETURN\n(GND_IN -> GND).  Device:L_Ferrite_Coupled has identical pin numbering if you would rather\nhave the ferrite-core graphic.\nIn the KiCad 10 Device library a diode's pin 1 is the CATHODE (K) and pin 2 is the ANODE (A),\nand the unrotated symbol draws the cathode on the LEFT.  D1 and D3 are rotated here so their\ncathodes face the nodes named in the net table; check polarity by the K / A pin names, not by\npin-number habits carried over from KiCad 9 or earlier.\nD2 is Device:D_TVS, whose pins are A1 / A2 -- that is the BIDIRECTIONAL TVS symbol, while the\nSMBJ24A is a UNIdirectional part.  Pin 1 is wired to VBAT_PROT so that pad 1 (the cathode band\non an SMB body) lands on the rail.  Either swap in a unidirectional symbol, or change the part\nnumber to SMBJ24CA if a bidirectional clamp is what is actually wanted.",
     177.8, 11.43, 103.19, 32.29),
    ('COMMON-MODE CHOKE AND THE SPLIT GROUND -- DO NOT "TIDY" THIS\n\nGND_IN (connector side) and GND (board side) are SEPARATE NETS, joined only\nthrough choke winding B. Nothing else may bridge them -- no wire, no capacitor,\nand on the PCB no ground-plane copper.\n\nThe usual way this gets broken is CAPACITIVE, not a wire: a decoupling cap from\nVBAT_PROT (upstream) to GND (downstream) bridges winding A\'s input to winding\nB\'s output, giving HF a path straight around the choke. The circuit then works\nperfectly and filters nothing, and no ERC or DRC check will complain.\n\nThat is why C1 sits on VBAT_F (downstream) and the TVS anode sits on GND_IN\n(upstream).\n\nBUILD OPTION: fit EITHER L2 (the choke) OR R2+R3 (0R links that short the\nwindings). Links give the simple tied-ground case for the first prototype;\nthe footprint is present either way so fitting a real choke later needs no\nboard revision.\n\nLAYOUT (Task 8): the ground plane must not bridge the choke.\n\nGND_IN is a LOCAL label, never a power symbol.  A second power symbol named GND\nwould merge the two returns globally and silently defeat the whole arrangement.',
     20.32, 106.68, 150.0, 42.79),
    ('P-CHANNEL MOSFET ORIENTATION (Q1) -- DELIBERATE. DO NOT "CORRECT" IT.\nDRAIN (pin 3) is on the incoming, fused side.  SOURCE (pin 2) is on the load side (VBAT_PROT).\nReason: a P-channel body diode conducts DRAIN -> SOURCE.  In this orientation the body diode\nconducts at power-up and pulls VBAT_PROT up to roughly the feed voltage; R1 holds the gate near\nthe incoming return GND_IN, so Vgs goes to about -11.4 V and Q1 turns fully on.  The stage is\ntherefore self-starting.  Under reverse polarity the body diode is reverse-biased and Vgs is\npositive, so Q1 stays off and the reverse path is BLOCKED.\nWired the other way round (source toward the fuse) reverse polarity would pass straight through\nthe body diode and this protection would do nothing at all.\nThe implementation plan\'s Task 3 text describes the opposite orientation.  This sheet is right;\nthe plan text is wrong.\nBEFORE FABRICATION: check the G/S/D pin assignment of Q1 against the SQJ415EP datasheet pinout,\nand make sure the footprint you assign maps pad-for-pad onto pins 1 = G, 2 = S, 3 = D.',
     20.32, 11.43, 150.0, 25.29),
    ("VALUE NOTES\nR1 = 1M is a MINIMUM, not a preference.  R1 is the only permanent load across the gate-source\npath and it sits on the always-on feed, so it draws current in deep sleep: 1 MOhm at 12 V is\n12 uA.  Anything below 1 MOhm breaks the sleep-current budget -- do not drop it to speed up\ngate turn-off.  R1's return is on GND_IN, not on board GND: the gate must reference the return\nthe battery is actually connected to, or the reverse-polarity behaviour is referenced to the\nwrong node.\nR2 and R3 = 0R links.  Fit EITHER L2 OR R2+R3, never both -- see the split-ground note.\nD1 = 12 V Zener, clamps Vgs on a positive transient (Vgs(max) for this class of part is about\n+/- 20 V).  D2 = SMBJ24A load-dump clamp.  D3 = 40 V Schottky feeding the logic rail.\nC3 = 220 uF electrolytic bulk; C1 / C2 / C4 / C5 ceramic; L1 = 10 uH, the series element of the\npi filter; L2 = the common-mode choke.  F1 = 10 A.",
     177.8, 78.74, 103.19, 23.54),
    ('NOT DRAWN: THE DNP SECOND FEED AND SECOND SCHOTTKY (spec section 4.4)\nSpec 4.4 asks for a second 12 V feed and a second Schottky as FOOTPRINTS ONLY, fitted\nDo-Not-Populate, so that an ideal-diode OR can be retrofitted without a board respin.  Those\nparts (J2 / F2 on net VBAT_B, and a second Schottky from VBAT_B into VLOGIC_IN) are\nintentionally absent here.  Add them as DNP symbols before PCB layout if you want them in the\nnetlist -- a footprint that is not in the netlist will not be placed on the board.',
     177.8, 62.87, 103.19, 13.04),
]
